### ISSUE TITLE
trainNetwork

### ISSUE THREAD

**Issue by jktms** [Skythianos/No-Reference-Video-Quality-Assessment-Based-on-the-Temporal-Pooling-of-Deep-Features#4]
when run the 'net = trainNetwork(trainFrames, lgraph, options)'
it shows:
              in trainNetwork（line 165）
              Invalid validation data. The output size (2) of the last layer does not match the number of classes (4).

I saw the function transferLearingInceptionResNetV2.m.I don't know what should i do with it .

**Comment by Skythianos** [comment]
I checked the program yesterday. You should copy the videos of KoNViD-1k database into the KoNViD_1k_videos folder and run the main.m MATLAB script.
